version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test
    working_directory: ~/app

  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test
    working_directory: ~/app

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - run:
          name: Deploy app
          command: echo "Deploying to production server"
    working_directory: ~/app

workflows:
  version: 2
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build # only test if the build job has completed
      - deploy:
          requires:
            - test # only deploy if the test job has completed
          filters:
            branches:
              only: master # only deploy if the master branch
